### ISSUE TITLE
Spec for DOMTokenList stringifier disagrees with every single implementation

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/dom#105] opened 2015-11-12 06:29 UTC
It looks like the spec for this got changed in 2012 in https://github.com/whatwg/dom/commit/8deff0eb9275dadec6fd41cc9eaeec93ee14bb54, after all browsers had already interoperably implemented the previous spec.  Simple testcase:

```
<div class=" a   b   c "></div>
<pre id="log"></pre>
<script>
  document.querySelector("pre").textContent = 
    document.querySelector("div").classList;
</script>
```

Per current spec, the value in the `<pre>` should be:

```
a b c
```

but all of Firefox, Chrome, Safari, IE (edge) make it 

```
 a   b   c
```

(with leading and trailing whitespace).  You can see a live testcase at http://jsfiddle.net/e3LwzL9d/

It's probably a good idea to revert to the old behavior, and similarly to have the `DOMSettableTokenList` getter for `value` just get the attribute value, so it stays in sync with the stringification behavior.  You can see a testcase for that case at http://jsfiddle.net/e3LwzL9d/1/ and it looks like this:

```
<iframe sandbox=" a   b   c "></iframe>
<pre id="log"></pre>
<script>
  document.querySelector("pre").textContent = 
    document.querySelector("iframe").sandbox.value;
</script>
```

Again, all browsers that implement `DOMSettableTokenList.value` (IE, Chrome, Firefox) return

```
 a   b   c 
```

here, not

```
a b c
```

**Comment by annevk** [comment] 2015-11-12 08:05
Wow, that is some sad serialization.

**Comment by annevk** [comment] 2015-11-12 08:05
Thank you for reporting this though!

**Comment by bzbarsky** [comment] 2015-11-12 14:45
Thanks for the quick fix!  I agree the nicer serialization would be nicer, but it doesn't seem worth the churn.

**Comment by ArkadiuszMichalski** [comment] 2015-11-12 17:01
Update steps for method like add(), remove() and toggle() is still in onboard? All browser don't do this now. 

And second, any plans add to DOMTokenList/DOMSettableTokenList other serialising variant (attribute or method) or iterator will be the only way to output all tokens from object?

**Comment by annevk** [comment] 2015-11-12 18:15
@ArkadiuszMichalski what do you mean, browsers don't do it? `<script>document.head.classList.add("x","y")</script>` in Live DOM Viewer clearly shows an attribute being added with as its value the tokens serialized.

No plans for exposing set serializing in some other way. And if you only use the `DOMTokenList` object to manipulate the attribute there shouldn't be a difference.

**Comment by ArkadiuszMichalski** [comment] 2015-11-12 18:39
@annevk I mean, when invoking this methods, that browsers don't set asociated attr's value to "ordered set serializer for tokens", we still have repeated tokens and white space in asociated attr's value.

Backing to serializing, ok, but previouse solution was better, actually we have xxx solution to get attr's value by using one command line, but now it's impossible for `DOMTokneList` and 'DOMSettableTokenList', so output all tokens from list needs more work. Basically it will be only inconvenient for testing and can live with that.

**Comment by annevk** [comment] 2015-11-13 06:35
If browsers don't set the attribute value correctly that does seem like a bug worth solving.

**Comment by ArkadiuszMichalski** [comment] 2016-03-31 19:18
@annevk 
> If browsers don't set the attribute value correctly that does seem like a bug worth solving.
Sure, we have some bugs open (at least for Gecko), but after 3 years nothing change. Is there any implementation where DOMTokenList contains only unique tokens? Have you any infos how its looks like in Edge, Webkit, eventually in Sevro? I once again check all this stuff for DOMTokenList and unfortunately there still exist differences between DOM and current implementations.

**Comment by annevk** [comment] 2016-03-31 19:22
Could you file a new issue @ArkadiuszMichalski? That's easier to track.

**Comment by ArkadiuszMichalski** [comment] 2016-03-31 20:08
Sure, here we go  https://github.com/whatwg/dom/issues/201

**Comment by mgol** [comment] 2016-04-06 10:47
Do I understand correctly that this issue was purely about `DOMTokenList#value` and all operations like `DOMTokenList#{add,remove,toggle}` should normalize the value, trimming it & collapsing whitespaces to single spaces?

I'm asking because Chrome fixed some of the issues in https://crbug.com/526282 (although not completely, see https://crbug.com/600964), Edge 13 has fixed the update steps and Safari Technical Preview did it as well.

**Comment by mgol** [comment] 2016-04-06 10:51
BTW, Safari Technical Preview normalizes the regular stringification reported here as well: http://output.jsbin.com/yupuse. Edge does it only on add/remove/toggle

**Comment by ArkadiuszMichalski** [comment] 2016-04-06 11:20
In short word (when reading spec) it it looks like:
- tokens (from `DOMTokenList`) are synchronized with associated attr, so if we change first of them then we should get effect on second (and vice versa). But `DOMTokenList` should trim whitespace, eliminate repeated token, and eliminate repeated whitespace. So it's normal that in some cases value in associated attr may differ from what is expressed by `DOMTokenList`. But using method like `add/remove/replace/toggle` (even when no passing any argument) should automatically update its associated attr value and clean it (remove duplicate token, white space, etc.)
- stringifire for `DOMTokenList is` the same as directly using `DOMTokenList.value` getter, so we should get associated attr's value. It's sad, better if we get serialized `DOMTokenList` (https://dom.spec.whatwg.org/#concept-ordered-set-serializer) because in DOM there is no any command to do this, so we must use other solution from ES, but if all browsers work like that so it's can be accept. 

So if Safari Technical Preview works as I describe above then I have to congratulate, finally we have some progress here. You can check some of this test:
https://github.com/whatwg/dom/issues/201#issue-145004189
https://github.com/whatwg/dom/issues/91#issue-111958217
https://github.com/whatwg/dom/issues/81#issuecomment-148913547
https://github.com/whatwg/dom/issues/81#issuecomment-149927265

**Comment by mgol** [comment] 2016-04-06 11:34
> https://github.com/whatwg/dom/issues/201#issue-145004189

I commented there.

> https://github.com/whatwg/dom/issues/91#issue-111958217

In Safari Technology Prevoew I get the same values as in Firefox which agree with values from comments.

> https://github.com/whatwg/dom/issues/81#issuecomment-148913547

Here I get this in Safari Technology Preview:
```
link.sizes: 32x32
sizes_attr.value: 32x32

link.sizes: 32x32 48x48
sizes_attr.value: 32x32 48x48

link.sizes: 48x48
sizes_attr.value: 48x48
```

> https://github.com/whatwg/dom/issues/81#issuecomment-149927265

This test doesn't work in Safari Technology Preview, `el[el_attr]` is not a DOMTokenList there for `ping` or `sandbox`

**Comment by mgol** [comment] 2016-04-06 11:39
> BTW, Safari Technology Preview normalizes the regular stringification reported on this very issue as well: http://output.jsbin.com/yupuse. Edge does it only on add/remove/toggle.

This means that Safari Technology Preview is no longer following the spec wrt serializing to string as it serializes immediately, i.e. it follows the requirement from before landing 2920fc15b9e894c45ff84c5d3bb77f7513ff50e5.

**Comment by cdumez** [comment] 2016-04-07 16:16
When we finally implement this in WebKit, the specification changes back :/
It would be unfortunate to have to restore the old behavior in WebKit given that I think the new behavior is cleaner.

**Comment by annevk** [comment] 2016-04-07 16:34
@cdumez I didn't know you had implemented it, sorry. Hopefully Safari Technology Preview will prevent this sort of thing going forward. @bzbarsky given that Safari does have the better behavior, what do you think?

**Comment by cdumez** [comment] 2016-04-07 16:53
Yes, checking Safari Technology Preview is a good idea since we don't release Safari very often and we are working on aligning WebKit's behavior with the spec more.

FYI, we already had WebKit nightly builds before Safari Technology Preview :)

**Comment by bzbarsky** [comment] 2016-04-07 18:22
@annevk I still think that all shipping browsers currently do something, and while that something may not be perfectly optimal it is interoperable and known to be web-compatible.  Changes to the behavior have the burden of proving web compat and convincing everyone to change, ideally on similar schedules....

**Comment by cdumez** [comment] 2016-04-07 19:16
It is this kind of back and forth that is not encouraging us to aggressively implement changes to the specification in the first place. This had been in the specification for a while and was requested by framework developers. Changing the specification after one engine finally implemented it seems a bit unfair.

In any case, we are unlikely to revert WebKit to the old behavior considering the new one is nicer (it seems people agree on this at least) and we spent time implementing it, unless we start getting reports of compatibility issues in the wild.

**Comment by mgol** [comment] 2016-04-07 19:43
The rules about `classList` serializing in the spec & in browsers have been changing *a lot* recently so I doubt the Web depends on any particular serialization. My point of view is that if the spec is logical, unlikely to be Web-incompatible and it's relatively easy for browsers to get patched so that they adhere to it then it's better that the browsers change instead of the spec. As some people like to say, the future is larger than the past; if the spec remains unintuitive but implemented the same everywhere, the Web will eventually start depending on it leaving us with it forever.

The fact that WebKit changed their implementation to adhere to the previous, more logical version of the spec only reinforces this opinion for me.

**Comment by annevk** [comment] 2016-04-08 04:18
@cdumez could you ping this thread once Safari ships with the better behavior? I'll flip the specification at that point.

**Comment by cdumez** [comment] 2016-04-08 17:03
@annevk : I'll do my best to remember to do so, thanks.

**Comment by ayg** [comment] 2016-04-10 14:21
@annevk I was working on this for Gecko (https://bugzilla.mozilla.org/show_bug.cgi?id=869788), although I don't know if/when it will land.  If I understood all this discussion, the spec is going to change back, so I should go ahead with it and let you know if we land before Safari, right?

**Comment by annevk** [comment] 2016-04-10 14:49
@ayg sounds good. In particular, we'd revert https://github.com/whatwg/dom/commit/2920fc15b9e894c45ff84c5d3bb77f7513ff50e5.

**Comment by ayg** [comment] 2016-04-10 18:03
@annevk Why wait?  If WebKit and Gecko are already changing to the other version, shouldn't the spec change now so everyone knows what the right behavior is to converge on?

**Comment by mgol** [comment] 2016-04-10 18:26
> If WebKit and Gecko are already changing to the other version, shouldn't the spec change now so everyone knows what the right behavior is to converge on?

Especially that the original report came from @bzbarsky who's on the Gecko team so if Gecko is changing there's no one else opposing at the moment.

**Comment by ArkadiuszMichalski** [comment] 2016-04-10 18:53
But are you sure that this revert will be web-compat? If someone start using `classList` instead of `className` (like in eample from https://github.com/whatwg/dom/issues/105#issue-116488665) may have problem because get different value. All current and previous stable browsers work here like spec says so I can understand BZ objections.

**Comment by cdumez** [comment] 2016-04-10 20:36
@ArkadiuszMichalski: There has been no issue reported since we've made the change in WebKit (granted, the change has not shipped in Safari yet but it does not some testing still).

IMHO, having duplicates or extra spaces is a corner case which is why I was not too worried about backward compatibility when I made the change in WebKit.

As I said before, if it turns out to be breaking sites, I will revert the change but there has been no issue so far and I do think it is worth trying to ship this change.

**Comment by bzbarsky** [comment] 2016-04-10 22:15
Gecko changing is not a given.  I have my concerns about web compat, and last I checked the changes being proposed to Gecko were causing performance regressions...

Anyway, I still think this is all going to involve a lot of work and a period of browsers not being compatible with each other for pretty dubious benefit, but I'm not going to stop people from trying to do it; I just have no plans to aid and abet.

**Comment by ayg** [comment] 2016-04-11 10:46
I expect to be able to fix it in Gecko without performance regressions.  I also agree the benefit is dubious, but if WebKit has already done it based on what was previously agreed upon and they don't want to change back, it's not very nice to change the spec from under them and make them non-conforming.  The behavior is also more useful.

Anyway, I guess we'll see if it causes regressions or not.

**Comment by ArkadiuszMichalski** [comment] 2016-04-11 12:19
One note, if I understood correctly, then we have:
- fix https://github.com/whatwg/dom/commit/2920fc15b9e894c45ff84c5d3bb77f7513ff50e5 for this bug change stringifire behaviour and getting `DOMTokenList.value`
- but this result https://github.com/whatwg/dom/issues/201#issuecomment-208048248 shows, that WebKit implemented earlier behavior also for setting `DOMTokenList.value`, what was changed in this fix https://github.com/whatwg/dom/commit/e48ced42e68ce540c8d7c05d43868082f9d86f11
So it looks like WebKit for this three cases has now something what was defined earlier, like this snapshot:
https://www.w3.org/TR/dom/#dom-domtokenlist-stringifier
https://www.w3.org/TR/dom/#dom-domsettabletokenlist-value
Of course change all of them requires changes in every stable browsers. On the other hand these actual definitions fit to the situation even when browsers for some IDL attribute use String (instead DOMTokenList/DOMSettableTokenList) which, in principle, for some of them still exists today.
```js
<script>

	var el_a = document.createElement("a");
	var el_area = document.createElement("area");
	var el_link = document.createElement("link");
	var el_iframe = document.createElement("iframe");
	var el_output = document.createElement("output");
	var el_th = document.createElement("th");
	var el_td = document.createElement("td");
	var el_html = document.documentElement;

	function supportSet(desc, el, attr){
		var status = "FAILD";
		console.log(desc);
		if (el[attr] != undefined){
			console.log(el.localName + "." + attr + ".constructor: " + el[attr].constructor);
			if (typeof el[attr] == "object"){
				status = "PASS";
			}
		}
		else{
			console.log("Completly not support this attr in element.");
		}
		console.log(status + "\n\n");
	}

	var desc_start = "Support DOMTokenList for ";

	supportSet(desc_start + "HTML and CLASS:", el_html, "classList");
	supportSet(desc_start + "HTML and DROPZONE:", el_html, "dropzone");
	supportSet(desc_start + "LINK and SIZES:", el_link, "sizes");
	supportSet(desc_start + "A and PING:", el_a, "ping");
	supportSet(desc_start + "AREA and PING:", el_area, "ping");
	supportSet(desc_start + "TH and HEADERS:", el_th, "headers");
	supportSet(desc_start + "TD and HEADERS:", el_td, "headers");
	supportSet(desc_start + "OUTPUT and FOR:", el_output, "htmlFor");
	supportSet(desc_start + "IFRAME and SANDBOX:", el_iframe, "sandbox");
	supportSet(desc_start + "LINK and REL:", el_link, "relList");
	supportSet(desc_start + "A and REL:", el_a, "relList");
	supportSet(desc_start + "AREA and REL:", el_area, "relList");

</script>
```
Which actually leads me to ask the question: what exactly is planning to change (if at all)?

**Comment by bzbarsky** [comment] 2016-04-11 13:36
"Agreed upon" is not a correct characterization of the 2012 change to the spec; as far as I can tell it was made by the editor without actually getting any sort of consensus reply from implementors, in the usual whatwg way....

That's mostly an indictment of some of the operating procedures of whatwg, though.  I agree that the change is not nice to Apple; I was not even aware they were planning to change their long-standing implenentation after so many years....

**Comment by annevk** [comment] 2016-04-11 14:10
@bzbarsky I'm not sure why you saw the need to flame. I think that change was discussed with implementers back then, but I can't find context. Unfortunately commit messages back then were lacking. Certainly since then almost all changes are made after discussion with implementers and stakeholders. Often as the result of PRs reviewed by said implementers.

**Comment by bzbarsky** [comment] 2016-04-11 14:16
I agree things have gotten better since then, yes.

**Comment by ayg** [comment] 2016-04-13 13:22
Smaug wants to know what Edge and Blink thing about changing to the new behavior: https://bugzilla.mozilla.org/show_bug.cgi?id=869788#c33

**Comment by annevk** [comment] 2016-04-14 07:53
@tkent-google and @foolip might be able to answer https://github.com/whatwg/dom/issues/105#issuecomment-209438536.

**Comment by foolip** [comment] 2016-04-14 13:02
@ayg, to be clear, is the question whether Blink will imeplement https://dom.spec.whatwg.org/#concept-dtl-serialize soonish? AFAICT, what the spec is already the behavior of Blink even though it stores the value separately from the attribute value. I haven't read all of the context though, if a change is needed please clue me in :)

**Comment by ayg** [comment] 2016-04-14 14:31
@foolip Test-case:

```
<!doctype html>
<div class=" a a"></div>
<script>
document.body.textContent = document.body.firstChild.classList;
</script>
```

Historically all browsers say " a a".  The proposed change to the spec would make it say "a", and WebKit reportedly already does.  I.e., stringifying classList removes duplicates and normalizes whitespace.

**Comment by foolip** [comment] 2016-04-14 15:11
Blink says " a a" for that, and the spec says "A `DOMTokenList` object’s **serialize steps** are to return the result of running get an attribute value given the associated element and the associated attribute’s local name." Does that not simply get the attribute value, or where does the normalization happen?

**Comment by ayg** [comment] 2016-04-14 15:33
Blink is in line with the current spec (as are IE and Firefox, and WebKit until recently).  We're discussing changing the spec by reverting 2920fc1.

**Comment by foolip** [comment] 2016-04-15 13:44
OK, I see. What the spec used to say seems reasonable to me, at least if https://dom.spec.whatwg.org/#concept-ordered-set-serializer can be used for two things as in the spec.

I don't have time to poke at this now, maybe @yoavweiss?

**Comment by rodneyrehm** [comment] 2016-04-17 14:45
As far as I understand reverting 2920fc1 will make [dom-domtokenlist-stringifier](https://dom.spec.whatwg.org/#dom-domtokenlist-stringifier) use [ordered set serializer](https://dom.spec.whatwg.org/#concept-ordered-set-serializer) instead of [serialize steps](https://dom.spec.whatwg.org/#concept-dtl-serialize). While that'll take care of weird whitespace, how does that effect the collapsing of duplicate tokens (`" a a"` -> `"a"` as hinted by @ayg)? The only explanation I have is that »[…] takes a **set** and returns the concatenation […]« implies unique values. If that's the case, can this be made slightly more explicit? Also [ordered set parser](ordered-set-parser) might need changing to produce an ordered set of unique values, which would then prevent `.item()` and the iterator from exposing the duplicates.

If I got this wrong, I have no idea how the collapsing of duplicate values (from source attribute) is achieved, if at all.

**Comment by ArkadiuszMichalski** [comment] 2016-04-17 15:34
@rodneyrehm all definitions are clear here, set is createt from attr's value by using [ordered set parser
](https://dom.spec.whatwg.org/#concept-ordered-set-parser). This algorithm skip unnecessary whitespaces and emits only unique tokens so sets will have only unique tokens. The question is what stringifier of this set should do: returns oryginal attr's value (like now defined in DOM and like stable browsers works) or returns results from (ordered set serializer)[https://dom.spec.whatwg.org/#concept-ordered-set-serializer] (what was defined earlier in DOM and only Safari Technology Preview land this).
And rewerting https://github.com/whatwg/dom/commit/2920fc15b9e894c45ff84c5d3bb77f7513ff50e5 change not only stringifier but also `DOMTokenList.value` getter, it would be strange to have a different behavior for `DOMTokenList.value` setter. Look this comment: https://github.com/whatwg/dom/issues/105#issuecomment-208313414.

**Comment by rodneyrehm** [comment] 2016-04-17 16:37
@ArkadiuszMichalski I'm an idiot, how did I not read that properly? Thanks for the clarification! :)

**Comment by yoavweiss** [comment] 2016-04-18 05:09
> OK, I see. What the spec used to say seems reasonable to me, at least if https://dom.spec.whatwg.org/#concept-ordered-set-serializer can be used for two things as in the spec.
> 
> I don't have time to poke at this now, maybe @yoavweiss?

I'm afraid I won't have time to tackle that in the next few weeks.

**Comment by ayg** [comment] 2016-08-16 15:13
@foolip, can you or someone give any sort of definitive answer on whether Blink is interested in changing back to what the old spec said, which is what WebKit now does but Gecko/Blink/Edge do not?  (Old spec said to collapse whitespace and remove duplicates, current spec says to return as-is.)  As a reminder, everyone used to interoperably implement the current spec, but WebKit changed to match the then-current spec and doesn't want to change back.  Gecko wants to know what Blink and Edge think.

@annevk, who can we ask about Edge?

**Comment by cdumez** [comment] 2016-08-16 15:54
FYI, the behavior of the old spec is now about to ship in Safari 10. There is no unshipping it in Safari 10 at this point. There has been no issue with regards to performance or compatibility since we've made the change.

**Comment by annevk** [comment] 2016-08-16 17:59
@TravisLeithead should be able to tell us about Edge.

**Comment by tkent-google** [comment] 2016-08-16 23:24
Blink can change back the behavior.

**Comment by ayg** [comment] 2016-08-17 10:53
@tkent-google What do you mean change "back"?  As far as I know, Blink never implemented the old spec's behavior.

As far as Gecko is concerned, it would require nontrivial work to change to meet the old spec, and I don't think the spec should have been changed to start with.  But if Edge and Blink are okay with changing, IMO we should change just to not make WebKit have wasted their time implementing what the spec said at the time.  (Although it's not my decision.)  But please let's not have any more spec changes to preexisting interoperable behavior like this unless we have majority implementer buy-in in advance.

**Comment by cdumez** [comment] 2016-08-23 15:50
@tkent-google : To be clear, would you be OK implementing the pre https://github.com/whatwg/dom/commit/2920fc15b9e894c45ff84c5d3bb77f7513ff50e5 behavior in Blink, similarly to what was done in WebKit [1] ?

I hope we can reach some agreement on this. I don't think anyone has disagreed that the pre https://github.com/whatwg/dom/commit/2920fc15b9e894c45ff84c5d3bb77f7513ff50e5 behavior was nicer for Web authors so far. WebKit actually made this change because there was interest from web authors.

The revert in the specification is very unfortunate given that this was implemented in Safari 10 and as you know we don't ship major Safari updates very often.

[1] https://bugs.webkit.org/show_bug.cgi?id=148589

**Comment by ayg** [comment] 2016-08-23 18:29
@cdumez Where did web authors exhibit interest?

**Comment by cdumez** [comment] 2016-08-23 18:33
@mgol who commented earlier on this thread, via our bug tracker.

**Comment by tkent-google** [comment] 2016-08-24 08:48
> @tkent-google: To be clear, would you be OK implementing the pre 2920fc1 behavior in Blink, similarly to what was done in WebKit [1] ?

Yes.

**Comment by ayg** [comment] 2016-08-24 13:05
@smaug----, @bzbarsky: Given that WebKit has changed and Blink is willing to, is Gecko willing to (assuming we have a good patch)?  If so, the spec should change back, and I guess I'll put fixing up the Gecko patch on my todo list.

**Comment by bzbarsky** [comment] 2016-08-24 13:47
I'd like to hear what the Edge people think, because what I do NOT think we should do is change behavior here more than once, and in particular I don't want to make the change only to have them object to it strenuously and get it reverted.

That said, if there is actually a good patch (i.e. one that does not regress performance and so forth), I would be ok with it if there is general buy-in from everyone.

**Comment by bzbarsky** [comment] 2016-08-24 13:49
Note also that "console" should not be a getter call to start with.  See https://github.com/servo/servo/issues/13010

**Comment by annevk** [comment] 2016-08-24 14:06
If Chrome, Safari, and Firefox ship, then we'll just align the specification. Having said that, it would be nice if @travisleithead could chime in.

**Comment by bzbarsky** [comment] 2016-08-24 14:08
> If Chrome, Safari, and Firefox ship, then we'll just align the specification

Sure, but then if Edge doesn't ship we just end up non-interoperable, which is arguably worse than what we used to have.  Except I guess we're already non-interoperable as of Safari 10.  :(

**Comment by annevk** [comment] 2016-08-24 14:17
Yes, we don't have interop. And interop with Safari 10 gives a much cleaner API.

**Comment by cdumez** [comment] 2016-08-24 14:46
I will try and test Edge today by the original bug report we got said that Edge had already implemented the old spec, which was another factor in our decision.

**Comment by ayg** [comment] 2016-08-24 15:36
To be clear, the only thing we're discussing here is something like

```
data:text/html,<!doctype html>
<div class="a a"></div>
<script>document.body.textContent = document.body.firstChild.classList</script>
```

which is "a a" per current spec, Chrome, Firefox, and Edge.  The old spec said to return just "a".

The current spec still says that when you call a method that mutates the list, it gets reserialized with whitespace collapsed and duplicates removed.  Nobody has explicitly objected to keeping this that I know of, although nobody (except I guess WebKit) implements this either.  See the first couple of comments in this thread, and #201.  Example test-case for this:

```
data:text/html,<!doctype html>
<div class="a a"></div>
<script>
document.body.firstChild.classList.add("b");
document.body.textContent = document.body.firstChild.classList;
</script>
```

which should be "a b" per spec but in non-WebKit browsers is "a a b".

@cdumez, to clarify, are you also not okay with dropping just the bit that was changed back in the spec (when no mutation methods are called)?  It's not obvious to me why it's more useful to authors to return "a" instead of "a a" in the test case I give here, since they have all the methods they need to deal with the logical contents of the list.  Why do authors need direct access to a string with duplicates removed and whitespace normalized?  If they do, per the current spec they can normalize the content attribute by doing something like .replace("a", "a") or .remove("nonexistent-token") (although non-WebKit UAs don't support this currently).

@bzbarsky, you only mentioned .classList stringification in your report here.  Do you also have a problem with the serialization steps being run on all the mutation methods, which non-WebKit browsers also interoperably don't do?  Or is that different for some reason?

**Comment by bzbarsky** [comment] 2016-08-24 15:40
I have a problem with specs and implementation not matching; that's what this bug was about for a particular instance I was aware of.  I was not aware of them also not matching on mutation methods.

**Comment by cdumez** [comment] 2016-08-24 21:57
I have tested Edge today and it does not get rid of duplicates in the serializer.

@annevk Don't we need a W3C bug so that Microsoft could chime in?

**Comment by cdumez** [comment] 2016-08-24 22:08
@ayg: I have talked to @rniwa and he seems to be OK with dropping sanitization for both the stringifier and the 'value' attribute. He even has a patch for it. Given this new information, I guess I would be OK too. It is unfortunate but I guess it makes everyone's life easier.

**Comment by foolip** [comment] 2016-08-25 08:18
Maybe email @travisleithead with www-dom on CC?

**Comment by ayg** [comment] 2016-08-25 11:22
@cdumez We still need agreement to keep the current spec with normalization on add/remove/etc., so I don't think there's any reason to change WebKit to partially revert to the current spec until we get consensus on whether that's what we actually want.  The original original spec didn't ever do normalization, and that's what all non-WebKit browsers currently do, so it's still possible Edge wants to revert back to that.

**Comment by ArkadiuszMichalski** [comment] 2016-08-25 20:33
@ayg But some normalization is done for that method, `remove("a")` for `" a a b b "` will remove all `"a"` and trim space (at least in the Edge / Chrome). In other site, invoking `add(a)` for `" b b b "` will return `" b b  a"` (retains all spaces). I don't check all methods, but  it would be convenient to have a consistent behavior for all of them, especially when Safari 10 land this normalization (removing duplicates and trim spaces) without any compatibility reports. And, per the current spec, we can normalize the content attribute by invoking `add()` or `remove()` without any argument.

Current definitions in spec seem most sense because:
Stringifire `DOMTokenList` is the same ass getter `DOMTokenList.value`.
Setter for attribute which operates on DOMTokenList (like 'Element.classList = ') is the same ass setter `DOMTokenList.value` and is the same ass setter `Element.className`, so we can stop using `className`.
Would be stragne changing only stringifire but not setter (if you still consider this change).

But it still does not matter if finally sets will not contain duplicates (https://github.com/whatwg/dom/issues/201) because it comes directly from the [definition](https://dom.spec.whatwg.org/#ordered%20sets).

**Comment by ayg** [comment] 2016-08-28 11:21
Test for current behavior: http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4418  Tested in Edge 25.10586, Firefox 50.0a2, Chrome 52:

* None of the browsers ever condenses duplicates, and none touches the attribute if no actual change is to be made (i.e., removing a token that's not present or adding one that already is).
* When adding a token that isn't already in the list, Edge normalizes whitespace, while Firefox and Chrome do not.
* When removing a token that is in the list, Edge and Chrome normalize whitespace, while Firefox does not.

So we should certainly spec that any change to the list normalizes whitespace, since that's not interoperable now anyway.  As far as the rest of what's in the spec, I don't know.  I think it would be easier to implement the current spec than the previous spec, because duplicate-checking is potentially expensive and might need less optimization if it's only from method calls.

I think we're still blocked here on hearing what Edge has to say.

@ArkadiuszMichalski We aren't arguing so much about what makes sense or is convenient.  We're arguing about whether it's worth it to change the spec where we already have interop.

**Comment by ayg** [comment] 2016-08-28 13:13
Seems Firefox is moving a bit more toward the current spec.  https://bugzilla.mozilla.org/show_bug.cgi?id=1293563

**Comment by ArkadiuszMichalski** [comment] 2016-08-30 14:13
Yep, now (after fix that bug) Firefox normalize whitespace for `remove()` and 'replace()'.

**Comment by cdumez** [comment] 2017-01-31 02:23
FYI, the DOMTokenList's stringifier no longer sanitizes tokens in WebKit as of <http://trac.webkit.org/changeset/206560>. WebKit should now be in-line with the latest spec.

**Comment by cdumez** [comment] 2017-01-31 02:28
I have noticed however that http://w3c-test.org/dom/lists/DOMTokenList-iteration.html expects us to not get rid of duplicates when iterating over the DOMTokenList (https://github.com/w3c/web-platform-tests/pull/4658). Unless I missed something, this does not seem to match the current spec. However, Firefox / Chrome seem to pass that test and Safari does not (because it gets rid of the duplicate).

**Comment by annevk** [comment] 2017-03-16 17:00
Okay, so the main thing to do be done here is that I need to file issues against the other browsers.

**Comment by annevk** [comment] 2017-03-16 17:10
Also https://bugzilla.mozilla.org/show_bug.cgi?id=869788 needs to be marked WONTFIX.

**Comment by annevk** [comment] 2017-03-16 17:17
Blink: https://bugs.chromium.org/p/chromium/issues/detail?id=600964 (was already filed)
Gecko: https://bugzilla.mozilla.org/show_bug.cgi?id=1347998
Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11297888/

Sorry about the delay and hopefully our new way of working that includes tests and early bugs will prevent this kind of problem going forward.

**Closed by annevk** 2017-03-16 17:17 UTC
