### ISSUE TITLE
[Range] Should the DOM range spec include an i18n warning?

### ISSUE THREAD

**Issue by sanketj** [whatwg/dom#1177] opened 2023-03-27 19:59 UTC
This came up during the highlight API i18n review: https://github.com/w3c/csswg-drafts/issues/5771. The DOM range API allows endpoints to be placed in the middle of characters that are made up of multiple unicode codepoints. This can cause internationalization problems for web authors or other APIs that utilize DOM ranges. Should the DOM range spec include a warning about this?

**Comment by xfq** [comment] 2023-03-28 02:22
Related: https://github.com/whatwg/dom/issues/933

**Comment by annevk** [comment] 2023-03-28 06:37
It seems like a duplicate of that issue? Any reason to keep both open?

**Closed** 2023-03-28 15:52 UTC
