### ISSUE TITLE
MutationObserver opportunity for memory leak.

### ISSUE THREAD

**Issue by trusktr** [whatwg/dom#482] opened 2017-07-27 00:19 UTC
There's a problem with MutationObserver.

**1)** Suppose we want to use [one MutationObserver to observe multiple elements](https://stackoverflow.com/questions/30807846/can-a-single-mutationobserver-object-observe-multiple-targets).

There's no way to stop observing just one of the observed elements. The `MutationObserver.prototype.disconnect()` method only allows us to stop observing *all* elements.

Therefore, when using a single MutationObserver to try and observe multiple elements in a tree, if one of those elements is permanently removed, there's no clean way to stop observing only that node while still observing other nodes.

This means that a naive developer (there's many *many* beginner programmers in the web) will never call `disconnect()`, and the observed node may stay in (leak into) memory.

---

**2)** Another approach is to use a single MutationObserver on the root node of a tree, with `subtree: true`, then in the callback try to determine the net changes that occurred in the whole tree, but this is [very difficult](https://stackoverflow.com/questions/38998599), and essentially requires one to write error-prone logic to reduce mutation records in the set of net changes in the tree, which ultimately leads to one simply ignoring the list of mutation records and using a DOM-diffing library.

The benefit of this approach is less likelihood for leaky code, `disconnect()` required to be called only when the root node is no longer needed to be observed.

---

**3)** Another approach is to use one MutationObserver per node-to-be-observed, and never use `subtree: true`, only `childList: true`.

The downside of this approach is higher CPU and Memory usage due to the need for one MutationObserver per observed node.

The result could be the same as one using the first approach, but with this approach cleanup is straight forward because `disconnect()` can be called on any observer to stop observing a specific node, which means less likelihood for leaks.

---

## Solution:

The simplest approach would be if `MutationObserver.prototype` had an `unobserve(node)` method. Or perhaps a node could be passed into `disconnect(node)`. We would be able to stop listening to specific nodes that way. 

The benefit would be the flexibility of approach **3)** but without the extra CPU and Memory overhead.

**Comment by trusktr** [comment] 2017-07-27 00:52
Let me better explain with a use case:

## Use Case:

I would like to observe an entire SVG DOM tree. Whenever anything in the tree changes, I want to map those changes to changes in a WebGL scene graph tree (f.e. create with a 2D library like Two.js or Pixi.js).

The result is an SVG DOM that can be manipulated (f.e. animated) and the result rendered in WebGL rather than the browser's implementation. It is easy to apply certain optimizations this way (because we can't touch the browser implementation).

I need to observe attribute changes and also observe when any nodes are added or removed anywhere in the tree.

## first approach

I could make a single MutationObserver, then I can traverse the SVG tree and observe every element in the tree. I want to observe attribute changes, and children being added and removed. For children added/removed, I would never use `subtree: true`, only `childList: true`.

If a child is removed, I need to stop observing it (uh oh).

I would have to `disconnect()` the single MutationObserver, then traverse the whole tree again and start observing everything again.

Ouch.

## second approach

I could make a single MutationObserver observing only the root `<svg>` element using `subtree: true`. When the observer callback is fired, I would have to analyze the list of mutation records to determine the net changes of the whole tree.

This defeats the purpose of having a mutation record list, because I will simply prefer to use a DOM-diffing library inside the callback to determine net changes in the whole SVG tree.

The bigger the SVG tree, the more CPU and Memory intensive this will be.

But at least I know I can easily *not* leak memory.

## third approach

Just like the first approach, except instead of one MutationObserver observing every node, I would have one MutationObserver per node for every node.

The rest is the same, except I now have the ability to stop observing certain nodes when they are no longer in the tree.

## fourth (ideal, not-yet-possible) approach

Instantiating a single MutationObserver then having it observe all the element in the SVG seems like it would be the most light weight, but it takes big effort not to leak memory.

If we had API to stop observing specific nodes, then this approach would be just like the first, except it would be very easy to stop observing nodes that are no longer in the SVG tree.

**Comment by trusktr** [comment] 2017-07-27 01:01
The fourth and first approach let me map changes in the SVG tree one-to-one with scene graph changes, without a diffing step. This means determining the changeset has time complexity as big as the changeset itself, whereas dom-diffing of the previous example may have time complexity that increases as the tree size increases even if the changeset stays the same.

**Comment by annevk** [comment] 2017-07-27 07:29
I think this is a duplicate of #126, but there's maybe more here? It would help a lot if you learned how to write down your problem more concisely. A wall of text isn't great for issues.

**Comment by trusktr** [comment] 2017-07-28 04:41
Sorry. It just boils down to #126, but I'll abstract some of the stuff here into a new issue: https://github.com/whatwg/dom/issues/484

**Closed** 2017-07-28 04:41 UTC
