### ISSUE TITLE
When moving APIs from other specs to DOM spec, ensure MDN is updated

### ISSUE THREAD

**Issue by smaug----** [whatwg/dom#710] opened 2018-10-25 08:41 UTC

**Comment by annevk** [comment] 2018-10-26 07:39
So this is about StaticRange et al I think.

In general we do now have a mechanism to notify MDN folks, but we haven't retroactively looked at what is out-of-date yet.

cc @whatwg/documentation

**Comment by smaug----** [comment] 2018-10-26 08:05
StaticRange is what reminded me of this. We've had similar issues several times.
But sounds great if there is some easy way to notify MDN folks.

**Comment by chrisdavidmills** [comment] 2018-10-30 14:30
@smaug---- so, I think the way it is set up, I get an email notification each time a change happens on each issue with the "impacts documentation" flag set on it.

This would be fine for me to use to add issues to our content roadmap (https://trello.com/b/LFl3umOX/mdn-content-roadmap). If the issue is somewhat obscure, a brief explanation of what needs to be done would also help ;-)

I could then write a comment saying I've added it to the roadmap, so people know, and I don't end up adding things twice or more.

**Comment by sideshowbarker** [comment] 2018-10-31 01:52
> @smaug---- so, I think the way it is set up, I get an email notification each time a change happens on each issue with the "impacts documentation" flag set on it.

Actually the "impacts documentation" flag doesn’t cause any notifications to be sent. Instead, the notifications get sent only if somebody adds a comment with @whatwg/documentation.

The "impacts documentation" flag just enables a view of all the documentation-related issues and PRs; see for example https://github.com/whatwg/html/labels/impacts%20documentation

**Comment by chrisdavidmills** [comment] 2018-10-31 08:50
> Actually the "impacts documentation" flag doesn’t cause any notifications to be sent. Instead, the notifications get sent only if somebody adds a comment with @whatwg/documentation.

Ah, OK, got it. Well, as long as they are sent, this is useful to me ;-)

**Comment by annevk** [comment] 2018-12-14 14:02
I created https://github.com/whatwg/meta/pull/121 to document this policy for all WHATWG maintainers (aka authors/editors and anyone paying attention really). Once that's merged this'll be closed.

**Closed** 2018-12-14 17:34 UTC
Labels: impacts documentation
