### ISSUE TITLE
Specify ShadowRoot.innerHTML

### ISSUE THREAD

**Issue by sideshowbarker** [whatwg/dom#393] opened 2017-01-06 03:03 UTC
`innerHTML` is currently implemented as a property of `ShadowRoot` in both WebKit and Blink

(There’s been talk of moving it to `DocumentFragment`  but for that to happen somebody needs to do the work of coming up with what it does.)

**Comment by annevk** [comment] 2017-01-06 07:47
This is a duplicate of https://github.com/w3c/DOM-Parsing/issues/21. I thought about the idea of merging all that into DOM and I would support someone undertaking such an effort, but it's not going to be me for now.

**Closed by annevk** 2017-01-06 07:47 UTC
